### ISSUE TITLE
CalibrationFileGenerator Crashes if you try to run it in Windows with installed ARToolkit5

### ISSUE THREAD

**Issue by ScottJohnson2718** [qian256/HoloLensCamCalib#1]
I compiled and ran the scripts/ARToolkitCalibrationFileGenerator.cpp.  It crashes on this call
	arParamObserv2Ideal(dist_factor, ox, oy, &ix, &iy, dist_function_version);

The problem in my installation is:

#define ARDOUBLE_IS_FLOAT

I am linking against the libs in the installed version for Windows (C:\Program Files (x86)\ARToolkit5\lib) and it crashes if you keep that define above.
So simply undefine that and change the code where it uses floats to ARdouble and it runs.

**Comment by qian256** [comment]
Thanks! Fixed now
