### ISSUE TITLE
Setup details

### ISSUE THREAD

**Issue by tsteffelbauer** [qian256/HoloLensCamCalib#2]
Hi,

could you provide some additional information on how to setup this project? 
What versions of python/opencv/json are you using? 
Is it necessary that the raw pictures are 896x504?

Thanks in advance.

**Comment by qian256** [comment]
Hi @tsteffelbauer ,
I was using Python3 and OpenCV3. I think it should be compatible with python2 and opencv2, as long as opencv for python is correctly setup. JSON comes with python.
It is necessary to use raw pictures of 896x504.
First, you have determine what is the resolution you would like to use for your computer vision application. If it is 896x504, then the camera needs to be calibrated with that resolution. It is recommended to use 896x504 for real-time vision algorithms.

**Comment by CommanderLee** [comment]
Hi,
Do I need to set up my HoloLens to capture 896x504 pictures? I tried with Device Portal and got 1408*792 pictures. Thanks.

**Comment by arjdev69** [comment]
Hi @qian256, 

how to configure these files in unity 
"hololens896x504.dat" "hololens896x504.json and hololens896x504.yaml".

thank you.

**Comment by yukilikespie** [comment]
Hello @qian256 ,
Do you have any chance the project for the ARToolKitCalibrationFileGenerator.cpp ? I have tried to compile it, with no avail. I am not sure what libraries did I miss and I keep getting error over error because of them.
Thank you in advance.

**Comment by qian256** [comment]
Hi @jobino , if you use HoloLensARToolKit, then copy the .dat file to StreamingAsset folder. In the Unity  Editor for ARUWPController, there is a field "Camera Param Filename", modify that according to your own .dat

**Comment by qian256** [comment]
Hi @CommanderLee , I used my own Unity application to take pictures and send back to PC. If you want to request that Unity project, send me an email. I may post that application in this repo sometime in the future.

**Comment by grilledalready** [comment]
Hi @qian256 
Can you send me the unity project used to capture the images.Thanks.My email id is burnoutsree3@gmail.com.Thanks
