### ISSUE TITLE
Calibration patterns

### ISSUE THREAD

**Issue by araujokth** [qian256/HoloLensCamCalib#3]
Thanks for the great contributions for Hololens! I was now trying to use this project with my Hololens and was trying to find the "far" pattern you used online but couldnt manage. I found the "near" one though, in the artoolkit repo. 

Thanks a lot for the help!

**Comment by qian256** [comment]
Hi sorry for the delay. By pattern, do you mean the checkerboard? I was using OpenCV checkerboard, and generated my own for the "far" one.
