### ISSUE TITLE
Output error when running script

### ISSUE THREAD

**Issue by araujokth** [qian256/HoloLensCamCalib#4]
Hi,

I was now running your script on my Ubuntu 16.04 and get the following error

~/HoloLensCamCalib$ python calibrate.py --square_size 0.03 --pattern_width 7 --pattern_height 5 data1/raw/*.jpg
data1/raw/20170614_064153_HoloLens.jpg
processing data1/raw/20170614_064153_HoloLens.jpg... ok

RMS: 0.248947908729
camera matrix:
 [[ 624.6142862     0.          683.96168577]
 [   0.          615.58413133  381.0986102 ]
 [   0.            0.            1.        ]]
distortion coefficients:  [ 0.01878055 -0.06607193  0.0011638   0.00460311  0.        ]

Undistorted image written to: ./output/20170614_064153_HoloLens_chess.png_undistorted.png
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data

Do you know why this could be happening? 

I have installed OpenCV 3.2.0 [(following these instructions)](http://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/) and running with Python 3.5. I can see that the raw image is generated in the output folder, but there is an error with the undistorted image.

Thanks for the help!

**Comment by araujokth** [comment]
Hi,

I managed to get the correct output after changing the directory of the images to "data" only and then not specifying the folder when running the script. It was a bit strange since the folder was correct though.

In any case, I was now trying to run the script to create the .dat file (ARToolKitCalibrationFileGenerator.cpp).  Any chance you could share how you did your ARToolKit setup in order for this to compile? I have come to realize that my problem is that I did not setup ARToolKit well on my Ubuntu machine. as the instructions are quite messy on their github, so will try to go for Windows instead now.

**Comment by qian256** [comment]
I was doing the conversion on Windows machine. In the recent commit, I pushed the VS project with precompiled ARToolKit binaries. If you want to run the ARToolKitCalibrationFileGenerator.cpp seamlessly on Ubuntu, what you need is to get ARToolKit5.3.2 on Ubuntu, include the AR.h path, and link to libAR.so (I guess).
